import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfReader;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Text;

public class ThirdLab {

    public static void main(String[] args) throws Exception {

        PdfFont font = PdfFontFactory.createFont("Shrift.ttf", "CP1251", true);
        PdfWriter writer = new PdfWriter("res.pdf");
        PdfReader reader = new PdfReader("Shablon.pdf");
        PdfDocument pdf = new PdfDocument(reader, writer);
        Document document = new Document(pdf);
        document.setFont(font);
        Paragraph p = new Paragraph(new Text("Банк Санкт-Петербург"));
        p.setFixedPosition(35, 786, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("685568568"));
        p.setFixedPosition(55, 750, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("КПП 46364"));
        p.setFixedPosition(198, 750, 100);
        p.setFontSize(10);
        document.add(p);
        String whoget = "Конищев В.А.";
        p = new Paragraph(new Text(whoget));
        p.setFixedPosition(35, 737, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("5795975967"));
        p.setFixedPosition(353, 786, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("37000"));
        p.setFixedPosition(353, 775, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("56865"));
        p.setFixedPosition(353, 749, 100);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("19 мая"));
        p.setFixedPosition(192, (float) 681.7, 100);
        p.setFontSize(13);
        document.add(p);
        p = new Paragraph(new Text("18"));
        p.setFixedPosition((float) 250.4, (float) 681.7, 100);
        p.setFontSize(13);
        document.add(p);
        p = new Paragraph(new Text("1"));
        p.setFixedPosition(162, 681, 1000);
        p.setFontSize(14);
        document.add(p);
        p = new Paragraph(new Text(whoget));
        p.setFixedPosition(100, 638, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("ООО ТИГР"));
        p.setFixedPosition(100, 605, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("№(547) от (01.06.2020)"));
        p.setFixedPosition(100, 580, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("Интернет и телефония"));
        p.setFixedPosition(65, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text("1"));
        p.setFixedPosition(355, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text("1"));
        p.setFixedPosition(322, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        double price = 34066.0; 
        p = new Paragraph(new Text(String.valueOf(price)));
        p.setFixedPosition(390, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text(String.valueOf(price)));
        p.setFixedPosition(457, 540, 1000);
        p.setFontSize(12);
        document.add(p);
        p = new Paragraph(new Text(price + " руб."));
        p.setFixedPosition(450, 491, 1000);
        p.setFontSize(9);
        document.add(p);
        p = new Paragraph(new Text("0 руб."));
        p.setFixedPosition(450, 479, 1000);
        p.setFontSize(9);
        document.add(p);
        p = new Paragraph(new Text(price + " руб."));
        p.setFixedPosition(450, 466, 1000);
        p.setFontSize(9);
        document.add(p);
        p = new Paragraph(new Text("Заколдаев Д. А."));
        p.setFixedPosition(451, 334, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("Заколдаев Д. А."));
        p.setFixedPosition(237, 334, 1000);
        p.setFontSize(10);
        document.add(p);
        p = new Paragraph(new Text("1 на сумму " + price + " руб."));
        p.setFixedPosition(122, 451, 1000);
        p.setFontSize(9);
        document.add(p);
        document.close();
    }
}
